#!/bin/bash

#run cstacks0_R

#get stacks build
tar -xzvf stacks-2.0-build.tar.gz
rm stacks-2.0-build.tar.gz

#define variables
PROCESS=$1
RUN_NAME=$2
CPUS=$3

N=$4

#get files from previous step
cp /mnt/gluster/cdrummond/${RUN_NAME}_${PROCESS}/stacks.tar.gz ./tmp/
cd ./tmp
tar -xzvf stacks.tar.gz
rm stacks.tar.gz

#move into stacks directory to run it
cd ../stacks-2.0

#run cstacks
./cstacks -o ../tmp/stacks -n $N -p $CPUS -s ../tmp/stacks/sample3 -s ../tmp/stacks/sample5 -s ../tmp/stacks/sample9 -s ../tmp/stacks/sample11 -s ../tmp/stacks/sample15 -s ../tmp/stacks/sample17 -s ../tmp/stacks/sample21 -s ../tmp/stacks/sample22 -s ../tmp/stacks/sample23 -s ../tmp/stacks/sample24 -s ../tmp/stacks/sample25 -s ../tmp/stacks/sample26 -s ../tmp/stacks/sample27 -s ../tmp/stacks/sample28 -s ../tmp/stacks/sample29 -s ../tmp/stacks/sample30 -s ../tmp/stacks/sample31 -s ../tmp/stacks/sample32 -s ../tmp/stacks/sample33 -s ../tmp/stacks/sample34 -s ../tmp/stacks/sample35 -s ../tmp/stacks/sample36 -s ../tmp/stacks/sample37 -s ../tmp/stacks/sample38 -s ../tmp/stacks/sample39 -s ../tmp/stacks/sample40 -s ../tmp/stacks/sample41 -s ../tmp/stacks/sample42 -s ../tmp/stacks/sample43 -s ../tmp/stacks/sample44 -s ../tmp/stacks/sample45 -s ../tmp/stacks/sample46 -s ../tmp/stacks/sample48

#note: include a -s flag for every sample that you want to add to the catalog

#tar up job output
cd ../tmp/
tar -czvf stacks.tar.gz stacks/

cp stacks.tar.gz /mnt/gluster/cdrummond/${RUN_NAME}_${PROCESS}/
